version: "3.0"

services:
  payserver_mongo:
    image: mongo:4.0.17
    container_name: "tower_mongo"
    environment:
      MONGO_LOG_DIR: /dev/null
    volumes:
      - tower_mongo_db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --storageEngine=wiredTiger --logpath=/dev/null # --quiet
    networks:
      - tower_local_network

  tower:
    build:
      context: ./
    hostname: tower
    container_name: tower
    volumes:
      - ./server:/node/server:rw
      - ./node_modules:/node/node_modules:rw
      - ./package.json:/node/package.json:rw
    ports:
      - 8000:8000
      - 9229:9229
    environment:
      NODE_MONGODB: tower_mongo:27017
    networks:
      - tower_local_network

volumes:
  tower_mongo_db:

networks:
  tower_local_network:
    external: true